# Generated by Django 3.2 on 2021-05-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0002_alter_experiencia_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
